title: Manyfold
description: Organise your 3d print files
theme: just-the-docs
color_scheme: dark
logo: "/images/logo.png"
url: https://manyfold.app

aux_links:
  Source Code: https://github.com/manyfold3d/manyfold
  Roadmap: https://github.com/orgs/manyfold3d/projects/4/views/1

collections:
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title:output_ext

callouts:
  important:
    title: Important
    color: red
  note:
    title: Note
    color: yellow
  info:
    title: Info
    color: blue
  todo:
    title: TODO
    color: grey-lt
  good:
    title: Good
    color: green
  ok:
    title: OK
    color: yellow
  bad:
    title: Bad
    color: red
  na:
    title: Not Assessed
    color: purple
