title: Manyfold
description: Organise and share your 3d print files
theme: just-the-docs
color_scheme: dark
logo: "/images/roundel.svg"
url: https://manyfold.app

plugins:
  - jekyll-feed

aux_links:
  Roadmap: /features
  Contribute: /about/contribute
  Source: https://github.com/manyfold3d/manyfold

collections:
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title:output_ext
  installation:
    output: true
    permalink: "/get-started/:path"
    sort_by: order

callouts:
  important:
    title: Important
    color: red
  note:
    title: Note
    color: yellow
  info:
    title: Info
    color: blue
  todo:
    title: TODO
    color: grey-lt
  devquote:
    title: Quote from developer
    color: grey-lt
  good:
    title: Good
    color: green
  ok:
    title: OK
    color: yellow
  bad:
    title: Bad
    color: red
  na:
    title: Not Assessed
    color: purple

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      excerpt_separator: "

      "
